---
- name: List all files
  hosts: all
  connection: local
  tasks:
        - name: list files
          shell: "ls -lstr"
          register: out_put

        - name: debug
          debug:
               msg: "{{ out_put.stdout_lines }}"
